#!/bin/sh

# get submodules
cd "$HOME"

# setup brew
echo "Installing brew packages"
brew tap railwaycat/emacsmacport
brew cask install emacs-mac
brew install fish ripgrep ffmpeg imagemagick deno vim tldr neofetch htop fzf cloc yadm

# setup emacs
echo "Installing emacs packages"
if [ ! -d "$HOME/.emacs.d" ]; then
  git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
  ~/.emacs.d/bin/doom install
fi

# install plugs
echo "Installing vim packages"
vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
