#!/usr/bin/env sh

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

setxkbmap -option "ctrl:nocaps"
xsetroot -solid '#ffffff'
picom --experimental-backends &
nitrogen --restore &

# =========
# VARIABLES
# =========
Mod=Mod4
Term=kitty

# ============
# KEY BINDINGS
# ============
hc keyunbind --all # remove all existing keybindings

# window manager
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q       close_and_remove

# applications
hc keybind $Mod-Return spawn $Term
hc keybind $Mod-e      spawn emacsclient -c -a ""
hc keybind $Mod-space  spawn rofi -show run

# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u             split bottom 0.5
hc keybind $Mod-Shift-u       split top    0.5
hc keybind $Mod-o             split right  0.5
hc keybind $Mod-Shift-o       split left   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-f         floating toggle
hc keybind $Mod-Shift-f   fullscreen toggle
hc keybind $Mod-Mod1-f    set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-m   set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-p         pseudotile toggle

hc keybind $Mod-Shift-bracketleft  rotate
hc keybind $Mod-Shift-bracketright chain . lock . rotate . rotate . rotate . unlock
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-bracketright \
            or , and . compare tags.focus.curframe_wcount = 2 \
                     . cycle_layout +1 vertical horizontal max vertical grid \
               , cycle_layout +1
hc keybind $Mod-bracketleft \
            or , and . compare tags.focus.curframe_wcount = 2 \
                     . cycle_layout -1 vertical horizontal max vertical grid \
               , cycle_layout -1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# =====
# THEME
# =====
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set focus_follows_mouse on
hc set always_show_frame on
hc set frame_bg_transparent on
hc set frame_border_width 0
hc set frame_gap 24

hc attr theme.background_color '#00000001'
hc attr theme.active.color '#ffffff'
hc attr theme.normal.color '#404040'
hc attr theme.urgent.color '#ffaaaa'
hc attr theme.border_width 2

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors
hc set auto_detect_monitors on

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
done
