#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "Source Code Pro:Bold:12.0"
yabai -m config status_bar_icon_font         "Hack Nerd Font:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  1 2 3 4 5 6 7 8 9
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config focus_follows_mouse          on

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  32
yabai -m config bottom_padding               32
yabai -m config left_padding                 32
yabai -m config right_padding                32
yabai -m config window_gap                   32

# window border settings
yabai -m config window_border                on
yabai -m config window_border_width          2
yabai -m config window_border_radius         0
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color   0xff4C566A
yabai -m config normal_window_border_color   0xff2E3440

