#!/usr/bin/env sh

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  32
yabai -m config bottom_padding               32
yabai -m config left_padding                 32
yabai -m config right_padding                32
yabai -m config window_gap                   32

# Opacity
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 1.0

# window border settings
yabai -m config window_border                on
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xff8994a9
yabai -m config normal_window_border_color   0xff2E3440

# Rules for specific apps
yabai -m rule --add app="System Preferences" manage=off
yabai -m rule --add app="Übersicht" manage=off
yabai -m rule --add app="kitty" opacity=0.85
yabai -m rule --add app="Emacs" opacity=0.85
